version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    deploy:
      restart_policy:
        condition: any

  app:
    image: ghcr.io/emilypozzatti/trabalho_tarcisio_1:v1.0.40
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    networks:
      app_network:
        aliases:
          - app
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  proxy:
    image: ghcr.io/emilypozzatti/trabalho_tarcisio_nginx:v1.0.40
    ports:
      - "8080:80"
    networks:
      - app_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == grupo1-proxy
      restart_policy:
        condition: any

networks:
  app_network:
    driver: overlay

volumes:
  postgres_data: