name: Build and Deploy Django

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Django image
        run: docker build -t ghcr.io/emilypozzatti/trabalho_tarcisio_1:latest ./app

      - name: Push Django image
        run: docker push ghcr.io/emilypozzatti/trabalho_tarcisio_1:latest

      - name: Build Nginx image
        run: docker build -t ghcr.io/emilypozzatti/trabalho_tarcisio_nginx:latest ./nginx

      - name: Push Nginx image
        run: docker push ghcr.io/emilypozzatti/trabalho_tarcisio_nginx:latest